language: php

php:
  - "5.6"
  - "7.2"
  - "7.3"

before_script:
  - composer self-update
  - composer install

script:
  - ./bin/run_php_validate.sh
  - export SYMFONY_PHPUNIT_VERSION=5.7
  - XDEBUG_MODE=coverage php vendor/bin/simple-phpunit

after_script:
  - php vendor/bin/php-coveralls -v
